version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nodeprisma
        
  server:
    build: .
    volumes:
      - .:/usr/src/app
      - /user/src/app/node_modules
    ports:
      - '5000:5000'
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@db:5432/nodeprisma?schema=public'
